# Generated by Django 5.0.1 on 2025-05-03 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=80, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('profile_img', models.ImageField(blank=True, default='', null=True, upload_to='profile_imgs/')),
                ('background_img', models.ImageField(blank=True, default='', null=True, upload_to='background_imgs/')),
                ('bio', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
